---
description: SQLAlchemy 2.0 Async standards. Part 2 — ORM models, relationships, and query construction.
globs: api/app/database/models/**/*.py
paths:
  - "api/app/database/models/**/*.py"
alwaysApply: false
---


# ============================================================
# SQLAlchemy Standards
# Part 2
# ORM Models, Relationships & Query Construction
# ============================================================

# Declarative Mapping

Always use SQLAlchemy 2.x Declarative Mapping.

Allowed

```python
class UserModel(Base):
```

Never use legacy mapper() patterns.

---

# Base Class

All ORM models MUST inherit from the project's declarative Base.

Never create multiple declarative bases.

---

# Type Annotations

Every mapped attribute MUST use

Mapped[]

Example

```python
id: Mapped[int]
```

Never omit type annotations.

---

# mapped_column()

Always use

mapped_column()

Never use legacy

Column()

inside new models.

Good

```python
id: Mapped[int] = mapped_column(primary_key=True)
```

Bad

```python
id = Column(Integer, primary_key=True)
```

---

# Explicit Types

Always declare explicit SQL types.

Avoid implicit type inference for database columns.

Good

```python
name: Mapped[str] = mapped_column(String(255))
```

---

# Column Naming

Column names must match the database schema.

Do not rename legacy database columns simply for aesthetics.

Application naming is handled by domain entities.

---

# Table Names

Use the exact database table names.

Avoid automatic pluralization.

Never invent new naming conventions.

---

# Primary Keys

Every table MUST have a primary key.

Primary keys should remain immutable.

Never update primary keys.

---

# Foreign Keys

Always define ForeignKey constraints explicitly.

Never rely on implicit relationships.

---

# Nullable

Columns must accurately reflect database nullability.

Avoid unnecessary nullable=True.

---

# Defaults

Prefer database defaults over Python defaults for persistent values.

Examples

CURRENT_TIMESTAMP

AUTO_INCREMENT

UUID()

Avoid duplicate default logic.

---

# Server Defaults

Prefer server_default for values generated by the database.

---

# Indexes

Indexes belong in model definitions.

Document unusual indexes.

Avoid unnecessary indexes.

---

# Composite Indexes

Use composite indexes only when supported by query patterns.

Never create speculative indexes.

---

# Unique Constraints

Business uniqueness should be enforced by the database.

Never rely solely on application validation.

---

# Check Constraints

Business invariants requiring database enforcement should use CHECK constraints where supported.

---

# Relationships

Relationships should be explicit.

Always define

back_populates

Avoid backref.

---

# Relationship Direction

Relationships should model actual business relationships.

Avoid unnecessary bidirectional relationships.

---

# Relationship Loading

Never rely on default lazy loading.

Specify loading behavior intentionally.

---

# Lazy Loading

Business logic must never trigger implicit SQL.

Lazy loading is discouraged.

---

# Preferred Loading

Prefer

selectinload()

for collections.

Prefer

joinedload()

for single related objects when appropriate.

Choose intentionally.

---

# contains_eager()

Use contains_eager() only when the query explicitly joins related tables.

---

# N+1 Queries

N+1 queries are unacceptable.

Repositories must load required relationships eagerly.

Never allow loops that trigger database access.

Bad

```python
for user in users:
    print(user.roles)
```

---

# Cascades

Configure cascades explicitly.

Never depend on implicit cascade behavior.

---

# Delete Cascades

Database cascades should match business requirements.

Never delete related data accidentally.

---

# Passive Deletes

Use passive_deletes where database cascades are preferred.

---

# Viewonly Relationships

Mark relationships as

viewonly=True

when they should never modify persistence state.

---

# Association Tables

Many-to-many relationships should use explicit association tables.

Avoid hidden join logic.

---

# Query Construction

Only use

select()

Never use

session.query()

---

# Selecting Models

Good

```python
stmt = select(UserModel)
```

Bad

```python
session.query(UserModel)
```

---

# Filtering

Prefer explicit expressions.

Good

```python
UserModel.email == email
```

Avoid string-based filtering.

---

# Boolean Comparisons

Good

```python
UserModel.is_active.is_(True)
```

Avoid

```python
== True
```

---

# Ordering

Always specify ordering when result order matters.

Never rely on database default ordering.

---

# Pagination

Large datasets MUST be paginated.

Never return unbounded collections.

---

# Limit

Use sensible limits.

Protect the database from excessive result sets.

---

# Offset Pagination

Current project standard

LIMIT

OFFSET

Future cursor pagination can be introduced separately.

---

# execute()

Repositories execute statements using

```python
await session.execute(stmt)
```

Never use synchronous execute.

---

# scalar()

Use

scalar_one()

when exactly one row must exist.

Use

scalar_one_or_none()

when zero or one row is valid.

Avoid ambiguous scalar() usage.

---

# scalars()

Use scalars() when selecting ORM models.

Example

```python
users = result.scalars().all()
```

---

# first()

Avoid first() when uniqueness is expected.

Prefer

scalar_one()

or

scalar_one_or_none().

---

# one()

Use only when multiple rows indicate a programming error.

---

# EXISTS

Prefer EXISTS for existence checks.

Avoid selecting entire rows unnecessarily.

Good

```python
select(exists(...))
```

---

# COUNT

Use COUNT only when the count is actually needed.

Never count rows before fetching unless required.

---

# Projections

Only fetch required columns.

Avoid loading entire models unnecessarily.

Good

```python
select(UserModel.id, UserModel.email)
```

---

# DISTINCT

Use DISTINCT intentionally.

Never use it to hide incorrect joins.

---

# Aliases

Use aliased() for self-joins and complex queries.

Avoid confusing table reuse.

---

# Subqueries

Use subqueries only when they improve readability or execution plans.

Avoid deeply nested queries.

---

# CTE

Common Table Expressions are acceptable for complex reporting queries.

Keep them readable.

---

# Raw SQL

ORM is preferred.

Raw SQL requires documented justification.

---

# SQL Functions

Use SQLAlchemy functions.

Good

```python
func.count()
```

Avoid raw SQL strings.

---

# Domain Mapping

ORM models MUST be mapped into Domain Entities.

Example

ORM

↓

Mapper

↓

Domain

Never expose ORM models outside repositories.

---

# Mapping Layer

Mapping logic belongs in dedicated mapper functions.

Avoid mixing mapping with SQL construction.

---

# Domain Entities

Repositories return

Domain Entities

Never ORM Models.

---

# Immutability

Domain entities should be immutable whenever practical.

Persistence state belongs to ORM.

Business state belongs to Domain.

---

# Legacy Database

Legacy schemas should be respected.

Do not rename

tables

columns

constraints

unless migration is approved.

---

# Legacy Nullability

Preserve existing database semantics.

Application validation may be stricter.

Database mapping must remain accurate.

---

# Computed Columns

Computed columns should remain database-driven.

Do not duplicate computation in Python.

---

# Database Views

Views should map to read-only ORM models.

Never update database views unless explicitly supported.

---

# Materialized Views

Treat materialized views as read models.

Refresh strategy belongs outside repositories.

---

# Repository Queries

Repositories should expose business-oriented methods.

Good

get_active_users()

find_school()

find_teacher()

Avoid exposing arbitrary SQL builders.

---

# Reusable Queries

Extract repeated query fragments into private repository helpers.

Avoid duplication.

---

# Query Readability

Favor readability over clever query composition.

Long queries should be broken into logical steps.

---

# Cursor and Claude MUST NEVER

Generate session.query()

Generate legacy Column()

Generate ORM models without Mapped[]

Generate implicit lazy loading

Generate backref

Generate N+1 queries

Generate SELECT *

Generate unbounded queries

Generate ORM models outside repositories

Generate business logic inside ORM models

Generate string SQL filters

Generate == True

Generate raw SQL for simple queries

Generate duplicated mapping logic

Generate repositories returning ORM models

Generate automatic table renaming

Generate hidden joins

Generate first() where uniqueness is expected

Generate pagination without LIMIT

Generate implicit relationship loading

---

# Final Principle

ORM models describe database structure.

Domain entities describe business concepts.

Repositories translate between them.

Queries should be explicit, efficient, deterministic, and optimized for readability before cleverness.