---
description: Defines Alembic migration standards, schema evolution practices, migration lifecycle, naming conventions, and database version management.
globs: api/migrations/**/*.py, api/alembic.ini
paths:
  - "api/migrations/**/*.py"
  - "api/alembic.ini"
alwaysApply: false
---

# ============================================================
# Alembic Migration Standards
# ============================================================

# Philosophy

The database schema

is source code.

Every schema modification

must be

version controlled

reviewable

repeatable

deployable

predictable.

Never modify production schemas manually.

---

# Migration Ownership

Every schema change

must be implemented

through Alembic.

Never modify tables

outside migrations.

---

# One Change

One logical schema change

↓

One migration.

Avoid combining

unrelated schema changes

into a single migration.

---

# Migration Workflow

Change ORM Models

↓

Generate Migration

↓

Review Migration

↓

Test Migration

↓

Commit Migration

Never skip

manual review.

---

# Auto Generation

Alembic autogeneration

is only

a starting point.

Every generated migration

must be reviewed

before execution.

Never trust autogenerated SQL blindly.

---

# Naming

Migration names

must describe

the schema change.

Good

add_user_status_column

create_teacher_table

drop_unused_index

rename_school_code

Bad

update

fix

migration1

changes

temp

---

# Revision History

Never edit

existing migration history

after it has been shared.

Create a new migration

to modify previous changes.

---

# Sequential History

Migration history

must remain linear

whenever practical.

Avoid unnecessary merge migrations.

---

# Reversible

Every migration

should support

downgrade()

when practical.

Downgrades should restore

the previous schema.

---

# Upgrade

upgrade()

must contain

only forward schema changes.

Avoid unrelated application logic.

---

# Downgrade

downgrade()

must reverse

only the corresponding migration.

Never perform

unexpected data changes.

---

# Data Migrations

Separate

schema migrations

from

large data migrations

whenever possible.

Schema changes

should remain fast.

---

# Data Backfills

Large backfills

should execute

outside request handling.

Prefer

maintenance jobs

or dedicated scripts.

---

# Destructive Changes

Avoid destructive changes.

Examples

DROP TABLE

DROP COLUMN

DROP INDEX

must be carefully reviewed.

---

# Safe Schema Evolution

Prefer

Add

↓

Migrate

↓

Deploy

↓

Remove

instead of

Rename

↓

Break

Production deployments

should remain backward compatible

whenever practical.

---

# Renaming Columns

Prefer

new column

↓

copy data

↓

deploy

↓

remove old column

Avoid direct renames

in high-availability systems.

---

# Renaming Tables

Avoid renaming tables

unless absolutely necessary.

Prefer

new table

↓

data migration

↓

application migration

↓

cleanup.

---

# Nullable Columns

When adding

new required columns

prefer

nullable

↓

backfill

↓

NOT NULL

instead of

adding NOT NULL immediately.

---

# Defaults

Avoid relying

on application defaults

for schema evolution.

Database defaults

should be explicit

when required.

---

# Constraints

All constraints

must be created

through migrations.

Examples

PRIMARY KEY

UNIQUE

FOREIGN KEY

CHECK

NOT NULL

---

# Indexes

Indexes

must be created

through migrations.

Review

execution plans

before adding indexes.

Avoid unnecessary indexes.

---

# Foreign Keys

Foreign keys

must be intentional.

Review

cascade behavior

carefully.

---

# Large Tables

Schema changes

on large tables

must consider

locking

execution time

rollback strategy.

Avoid long blocking migrations.

---

# Legacy Database

Respect

existing schema.

Never rename

legacy tables

columns

constraints

without explicit approval.

---

# Raw SQL

Use Alembic operations

whenever possible.

Use raw SQL

only when

Alembic cannot express

the required change.

Document the reason.

---

# ORM Synchronization

ORM models

must remain synchronized

with migration history.

Never update models

without creating

the corresponding migration.

---

# Branching

Avoid multiple migration heads.

Maintain

a single migration lineage

whenever possible.

---

# Merge Migrations

Merge migrations

only when

parallel development

requires reconciliation.

---

# Testing

Every migration

must be tested

on

an empty database

and

an existing database

containing representative data.

---

# Production Testing

Critical migrations

should be validated

against

production-sized datasets

before deployment.

---

# Rollback Testing

Downgrades

should be tested

whenever supported.

Never assume

rollback works.

---

# Transactions

Allow Alembic

to manage migration transactions.

Avoid manual transaction handling

inside migrations.

---

# Application Logic

Never place

business logic

inside migrations.

Migrations modify

database structure

only.

---

# Environment

Migration configuration

belongs

inside

database/

or

Alembic configuration.

Avoid duplicated configuration.

---

# Deployment

Deploy schema changes

before

deploying code

that depends

on new schema

when backward compatibility

is maintained.

---

# Compatibility

Applications

should tolerate

mixed-version deployments

during rolling releases

whenever practical.

---

# Documentation

Complex migrations

should include

comments

explaining

why

the migration exists.

---

# Performance

Large migrations

should minimize

table locking

and

execution time.

Measure

before production deployment.

---

# Observability

Record

migration execution

duration

success

failure

version.

---

# Security

Migration scripts

must never contain

production credentials

hardcoded secrets

application tokens.

---

# Code Review

Every migration

requires code review.

Review

generated SQL

constraints

indexes

downgrades

performance implications.

---

# CI

Continuous Integration

should verify

migration integrity.

Tests should confirm

the schema

can be upgraded

from a clean database.

---

# Cursor and Claude MUST NEVER

Generate manual production schema changes

Generate edited historical migrations

Generate unrelated schema changes in one migration

Generate business logic inside migrations

Generate repository code inside migrations

Generate HTTP code inside migrations

Generate FastAPI imports inside migrations

Generate hardcoded credentials

Generate missing downgrade()

Generate destructive schema changes without warning

Generate duplicate migration heads

Generate application logic inside upgrade()

Generate application logic inside downgrade()

Generate migration scripts without review

---

# Example Workflow

Modify ORM Model

↓

Generate Alembic Migration

↓

Review Migration

↓

Run Local Upgrade

↓

Run Local Downgrade

↓

Run Tests

↓

Commit Migration

↓

Deploy

---

# Migration Checklist

Every migration should satisfy

✓ One logical schema change

✓ Descriptive name

✓ Reviewed

✓ Upgrade implemented

✓ Downgrade implemented when practical

✓ ORM synchronized

✓ Constraints reviewed

✓ Indexes reviewed

✓ Tested locally

✓ CI validated

✓ Production-safe

✓ No business logic

---

# Final Principle

Database schema evolution is a controlled engineering process.

Every schema change must be reproducible, reviewable, and safe to deploy.

Alembic migrations are the single source of truth for schema history and should evolve with the same discipline as application code.